# TODO
feature: Проект

spec:
  Удалить проект с целями:
    # куда перенесутся цели при этом
  # TODO:

  Смена ключа проекта с целями:
    # если поменять ключ то ключи у целей тоже поменяются?
  # TODO:
  
  Переход в настройки сразу после создания проекта:
  # TODO: